ALTER TABLE Photo
ADD CONSTRAINT TransIDForeignKey
FOREIGN KEY (TransID) REFERENCES Transaction(TransID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Photo
ADD CONSTRAINT PhotographerForeignKey
FOREIGN KEY (PName, PBDate) REFERENCES Photographer(PName, PBDate)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Landscape
ADD CONSTRAINT LIDForeignKey
FOREIGN KEY (ID) REFERENCES Photo(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Landscape
ADD CONSTRAINT LocationForeignKey
FOREIGN KEY (Place, Country) REFERENCES Location(Place, Country)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Abstract
ADD CONSTRAINT AIDForeignKey
FOREIGN KEY (ID) REFERENCES Photo(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Models
ADD CONSTRAINT MIDForeignKey
FOREIGN KEY (ID) REFERENCES Photo(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Models
ADD CONSTRAINT ModelForeignKey
FOREIGN KEY (MName, MBDate) REFERENCES Model(MName, MBDate)
ON DELETE CASCADE;

ALTER TABLE Influences
ADD CONSTRAINT InfluencedForeignKey
FOREIGN KEY (EPName, EPDate) REFERENCES Photographer(PName, PBDate)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Influences
ADD CONSTRAINT InfluencerForeignKey
FOREIGN KEY (RPName, RPDate) REFERENCES Photographer(PName, PBDate)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Transaction
ADD CONSTRAINT LoginForeignKey
FOREIGN KEY(LoginName) REFERENCES Customer(LoginName)
ON DELETE CASCADE ON UPDATE CASCADE;
